services:
    # PHP-Service (Laravel)
    app:
        build:
            dockerfile: Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - laravel-network
        depends_on:
            - db

    # Nginx-Service
    webserver:
        image: nginx:alpine
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./docker/nginx/ssl/:/etc/nginx/ssl/
        networks:
            - laravel-network
        depends_on:
            - app

    # PostgreSQL-Service
    db:
        image: postgres:13
        container_name: laravel-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - ./docker/postgres/:/docker-entrypoint-initdb.d/
        ports:
            - "5432:5432"
        networks:
            - laravel-network

    # pgAdmin-Service
    pgadmin:
        image: dpage/pgadmin4
        container_name: laravel-pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        ports:
            - "5050:80"
        networks:
            - laravel-network
        depends_on:
            - db

# Networks
networks:
    laravel-network:
        driver: bridge

# Volumes
volumes:
    postgres-data:
        driver: local
    pgadmin-data:
        driver: local
