name: Oracle VM Deployment

on:
    push:
        branches:
            - oracle-deploy

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository (nur FoodFlow)
              uses: actions/checkout@v3
              with:
                  sparse-checkout: |
                      projects/FoodFlow
                  sparse-checkout-cone-mode: false

            - name: Setup SSH
              run: |
                  mkdir -p ~/.ssh
                  echo -e "${{ secrets.SSH_PRIVATE_KEY }}" | sed 's/\r$//' > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H 140.238.222.190 >> ~/.ssh/known_hosts

            - name: Deployment auf Oracle VM
              run: |
                  ssh -i ~/.ssh/id_rsa ubuntu@140.238.222.190 << 'EOF'
                    set -e  # Stop execution if any command fails
                    trap 'php artisan up' EXIT  # Ensure app goes back online

                    cd /var/www
                    if [ ! -d "laravel" ]; then
                        mkdir -p /var/www/laravel
                    fi

                    # Sync ONLY the FoodFlow project
                    rsync -av --delete FoodFlow/ /var/www/laravel/

                    cd /var/www/laravel
                    php artisan down --render="errors::503"

                    composer install --no-dev --optimize-autoloader
                    php artisan migrate --force
                    php artisan db:seed --class=PatchNotesSeeder
                    php artisan cache:clear
                    php artisan config:cache
                    php artisan route:cache
                    php artisan view:cache

                    # Set permissions
                    chmod -R 775 storage bootstrap/cache
                    chown -R www-data:www-data /var/www/laravel storage bootstrap/cache

                    # Restart services
                    sudo systemctl restart php8.3-fpm
                    sudo systemctl restart nginx

                    php artisan up
                  EOF
